# -*- coding: utf-8 -*-
"""Hotel Booking Demand Forecasting Using SARIMAX.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QB2-9KkzIxqeetgaLwJaGv6Ey-tRo5N2

Install Libraries
"""

!pip install statsmodels pmdarima --quiet

"""pmdarima	Auto ARIMA Library	Automatically finds best (p,d,q) parameters

--quiet	Silent Mode	Hides unnecessary installation messages

Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

import warnings
warnings.filterwarnings('ignore')

"""Upload Dataset"""

df = pd.read_csv('hotel_bookings.csv')

df.head()

"""Explore Dataset"""

df.shape

df.info()

df.isnull().sum()

"""Handle Missing Values"""

df['children'] = df['children'].fillna(0)
df['country'] = df['country'].fillna('Unknown')
df['agent'] = df['agent'].fillna(0)
df['company'] = df['company'].fillna(0)

"""Create Reservation Date"""

df['reservation_status_date'] = pd.to_datetime(
    df['reservation_status_date']
)

df['reservation_status_date']

"""Aggregate Daily Bookings"""

daily_bookings = df.groupby(
    'reservation_status_date'
).size().reset_index(name='bookings')

daily_bookings.head()

"""Create Exogenous Variables

Average values per day
"""

daily_exog = df.groupby(
    'reservation_status_date'
).agg({
    'adr':'mean',
    'lead_time':'mean',
    'adults':'mean',
    'children':'mean',
    'total_of_special_requests':'mean'
}).reset_index()

"""Merge Data"""

data = pd.merge(
    daily_bookings,
    daily_exog,
    on='reservation_status_date'
)

data.head()

"""Set Date Index"""

data.set_index(
    'reservation_status_date',
    inplace=True
)

data.head()

"""Plot Bookings"""

plt.figure(figsize=(15,5))
plt.plot(data['bookings'])
plt.title('Daily Hotel Bookings')
plt.xlabel('Date')
plt.ylabel('Bookings')
plt.show()

"""Define Target and Exogenous Variables"""

y = data['bookings']

X = data[
    [
        'adr',
        'lead_time',
        'adults',
        'children',
        'total_of_special_requests'
    ]
]

"""Train-Test Split

80% Train

20% Test
"""

split = int(len(data)*0.8)

y_train = y[:split]
y_test = y[split:]

X_train = X[:split]
X_test = X[split:]

"""Build SARIMAX Model

Weekly Seasonality = 7
"""

model = SARIMAX(
    y_train,
    exog=X_train,
    order=(1,1,1),
    seasonal_order=(1,1,1,7)
)

result = model.fit()

print(result.summary())

"""Forecast Test Data"""

forecast = result.predict(
    start=len(y_train),
    end=len(y)-1,
    exog=X_test
)

forecast.head()

"""| Code                 | Description                                                                           |
| -------------------- | ------------------------------------------------------------------------------------- |
| `forecast`           | Variable used to store predicted booking values                                       |
| `result`             | The trained SARIMAX model object                                                      |
| `.predict()`         | Function used to generate predictions                                                 |
| `start=len(y_train)` | Prediction starts immediately after the training dataset ends                         |
| `end=len(y)-1`       | Prediction continues until the last record of the dataset                             |
| `exog=X_test`        | Uses the test set's external variables (ADR, Lead Time, Adults, etc.) for forecasting |

Evaluation Metrics
MAE
"""

mae = mean_absolute_error(
    y_test,
    forecast
)

print("MAE :", mae)

"""RMSE"""

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        forecast
    )
)

print("RMSE :", rmse)

"""MAPE"""

mape = np.mean(
    np.abs(
        (y_test - forecast)
        / y_test
    )
)*100

print("MAPE :", mape)

"""Accuracy"""

accuracy = 100 - mape

print("Accuracy :", accuracy,"%")

print("Number of zeros:", (y_test == 0).sum())

"""Check Forecast for NaN"""

print("Forecast NaN values:", forecast.isna().sum())

print(forecast.head())
print(forecast.tail())

mape = np.mean(
    np.abs(
        (y_test.values - forecast.values)
        / y_test.values
    )
) * 100

print("MAPE :", round(mape,2))

"""Calculate Accuracy"""

accuracy = 100 - mape

print("Accuracy :", round(accuracy,2), "%")

"""Verify Index Issue"""

print(y_test.index[:5])
print(forecast.index[:5])

"""| Metric   | Value          |
| -------- | -------------- |
| MAE      | 104.09         |
| RMSE     | 125.41         |
| MAPE     | Not Suitable   |
| Accuracy | Not Applicable |

Better Metric (R² Score)
"""

from sklearn.metrics import r2_score

r2 = r2_score(y_test, forecast)

print("R2 Score :", round(r2,4))

"""Auto ARIMA to find better parameters:"""

from pmdarima import auto_arima

auto_model = auto_arima(
    y_train,
    exogenous=X_train,
    seasonal=True,
    m=7,
    trace=True,
    suppress_warnings=True
)

print(auto_model.summary())

"""Auto ARIMA has found the best model for your hotel booking data.

Auto ARIMA Result
Best model: ARIMA(0,1,1)(0,0,0)[7]

========

| Parameter | Value | Meaning                      |
| --------- | ----- | ---------------------------- |
| p         | 0     | No Auto-Regressive component |
| d         | 1     | First-order differencing     |
| q         | 1     | One Moving Average term      |
| P         | 0     | No Seasonal AR               |
| D         | 0     | No Seasonal Differencing     |
| Q         | 0     | No Seasonal MA               |
| m         | 7     | Weekly seasonality checked   |
====

ARIMA(0,1,1)

Current Booking
↓
First Difference Applied
↓
Moving Average Effect Used
↓
Forecast

Build SARIMAX using Auto ARIMA parameters:
"""

from statsmodels.tsa.statespace.sarimax import SARIMAX

model = SARIMAX(
    y_train,
    exog=X_train,
    order=(0,1,1),
    seasonal_order=(0,0,0,7)
)

result = model.fit()

print(result.summary())

"""Forecast"""

forecast = result.predict(
    start=len(y_train),
    end=len(y)-1,
    exog=X_test
)

forecast.index = y_test.index

"""calculate Metrics"""

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

mae = mean_absolute_error(y_test, forecast)
rmse = np.sqrt(mean_squared_error(y_test, forecast))
r2 = r2_score(y_test, forecast)

print("MAE :", round(mae,2))
print("RMSE :", round(rmse,2))
print("R2 Score :", round(r2,4))

"""| Parameter                   | Result                                                    |
| --------------------------- | --------------------------------------------------------- |
| **Model Used**              | SARIMAX (Seasonal ARIMA with Exogenous Variables)         |
| **Target Variable**         | Hotel Booking Demand                                      |
| **Forecast Generated**      | Yes                                                       |
| **Seasonality Considered**  | Yes                                                       |
| **External Variables Used** | Yes                                                       |
| **Future Demand Predicted** | Yes                                                       |
| **Forecast Accuracy**       | Poor                                                      |
| **Business Readiness**      | Requires further improvement before real-world deployment |

The SARIMAX model successfully forecasted future hotel booking demand for 186 periods. The predicted booking demand ranges from approximately 136 to 410 bookings, indicating fluctuations in demand with an overall upward trend. These forecasts can assist hotel management in capacity planning, staffing decisions, and revenue optimization.
"""