# -*- coding: utf-8 -*-
"""Water_consumption data how to create using Google Collab step by step method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYRUZN83v4pyqob-8NO4o4ZY0CCnpIyj
"""

import pandas as pd
import numpy as np

# Create dates for 2025-2026
dates = pd.date_range(
    start='2025-01-01',
    end='2026-12-31',
    freq='D'
)

# Generate realistic water consumption data
np.random.seed(42)

water_consumption = (
    1250
    + np.random.randint(-80, 80, len(dates))
)

df = pd.DataFrame({
    'Date': dates,
    'Water_Consumption': water_consumption
})

df.to_csv(
    'water_consumption.csv',
    index=False
)

print(df.head())
print("\nTotal Records:", len(df))

